[package]
name = "c-custom"
edition = "2021"
version = "1.0.2"
build = "build.rs"

[build-dependencies]
cc = "1"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html



[dependencies]
