[package]
name = "rayon-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
error-chain = "0.12.4"
glob = "0.3.1"
image = "0.24.5"
rand = "0.8.5"
rayon = "1.6.1"
